language: node_js
node_js:
  - "stable"
root:
  dist:
    - xenial
  os:
    - linux
branches:
  only:
    - master
cache:
  npm: true
  timeout:
    - "5"
  directories:
    - ~/.cache/Cypress
install:
  - yarn install --frozen-lockfile
script:
  - yarn test
  - yarn coverage
  - yarn test:e2e
