language: node_js
node_js:
  - "stable"
root:
  dist:
    - xenial
  os:
    - linux
branches:
  only:
    - master
cache:
  timeout:
    - "5"
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test
  - yarn coveralls
