language: node_js
node_js:
  - "stable"
root:
  dist:
    - xenial
  os:
    - linux
branches:
  only:
    - master
cache:
  npm: true
  timeout:
    - "5"
  directories:
    # cache both npm modules and Cypress binary
    - ~/.npm
    - ~/.cache
install:
  - yarn install --frozen-lockfile
script:
  ## print all Travis environment variables for debugging
  # TODO: We can paralellize our tests in different stages
  - yarn test
  - yarn coverage
  - yarn test:e2e
